spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pokeguess
spring.datasource.username=pokeguess
spring.datasource.password=pokeguess

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true